---
- name: Get Config from ASAs
  asa_command:
    commands:
      - show running-config
  register: output
  when: ansible_network_os == 'asa'

- name: Write config to file in the repo folder
  copy:
    content: "{{ output.stdout_lines[0] | join('\n') }}"
    dest: "./HomeLabConfigs/{{ inventory_hostname }}.txt"
  when: ansible_network_os == 'asa'